server:
  port: 40191
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://jaeryurp.duckdns.org:40171/beabus
    username: beabus
    password: beabus123!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#mybatis:
#  config: mybatis-config.xml
#  mapper-locations: mybatis/mapper/*.xml